// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-K3BgixdJKXUUhFI0feWfrzJuPjZKLA',
    appId: '1:287416550915:web:48e9745b7abb083fe57036',
    messagingSenderId: '287416550915',
    projectId: 'e-commerce-9c167',
    authDomain: 'e-commerce-9c167.firebaseapp.com',
    storageBucket: 'e-commerce-9c167.appspot.com',
    measurementId: 'G-YVHGFFN1CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXiQxHpR_FUREAHMPmg691GGLzguXBlc',
    appId: '1:287416550915:android:83ebd4a30e33ea72e57036',
    messagingSenderId: '287416550915',
    projectId: 'e-commerce-9c167',
    storageBucket: 'e-commerce-9c167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdUz_ZMs4YjJWIb06_MmGxDWZpZnGas8',
    appId: '1:287416550915:ios:d2701e5484652408e57036',
    messagingSenderId: '287416550915',
    projectId: 'e-commerce-9c167',
    storageBucket: 'e-commerce-9c167.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
